- sample/src/main/java/com/polidea/rxandroidble/sample/SampleApplication.java
getInstance was renamed to create in 7ca4e0312ae898e369ba1e67bd9ec9245fb2a4d9
but wasn't changed here
> Sample: Use create instead of getInstance

- rxandroidble/src/main/AndroidManifest.xml
By removing this attribute, the user of the library will once again be able to choose whether to allow backups or not.
A simple summary of this common library issue can be found [here](https://github.com/navasmdc/MaterialDesignLibrary/issues/134).
Thank you for your hard work, and I love this library 👍
> Removed unnecessary allowBackup attribute from AndroidManifest.

- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/util/BleConnectionCompat.java
If the first condition is met, autoConnect has the right to be both `true` or `false`.
> Avoid forcing the value for autoConnect

- mockrxandroidble/src/main/java/com/polidea/rxandroidble/mockrxandroidble/RxBleConnectionMock.java
- mockrxandroidble/src/test/groovy/com/polidea/rxandroidble/mockrxandroidble/RxBleClientMockTest.groovy
- rxandroidble/src/main/java/com/polidea/rxandroidble/RxBleConnection.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/exceptions/BleException.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/RxBleConnectionImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/RxBleGattCallback.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/operations/RxBleRadioOperationMtuRequest.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/operations/RxBleRadioOperationMtuRequestTest.groovy
- sample/src/main/java/com/polidea/rxandroidble/sample/example1_scanning/ScanActivity.java
- sample/src/main/java/com/polidea/rxandroidble/sample/example2_connection/ConnectionExampleActivity.java
- sample/src/main/res/layout/activity_example2.xml
Since API 21, is possible to set the MTU connection parameter and send packet with length up to 512 bytes.
This implementation bring the support to the RxAndroidBle library.
I've also added the related tests method and updated the sample.
If you prefer I can set up a different activity in the sample for test this functionality.
I've also added the request for the location permission in the sample project.
Tested on a Nexus 5X with Nougat
I know that there is already another PR related to the MTU, but I've implemented as a separated function.
> Added support for requestMtu

- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/RxBleConnectionImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/RxBleGattCallback.java
Hi, first of all - nice library :) it really makes interaction with BLE interface a lot less painful
I have a BLE device that has a few characteristics with the same UUID (don't ask me why, I don't like that fact either), you can only tell the difference by looking at their `BluetoothGattDescriptor`s.
I'm setting up notifications for those characteristics with your library using:
`RxBleConnection.setupNotification(bluetoothGattCharacteristic)`
Then if the value of one of the characteristics changes, I'm getting a notification on all of those characteristics - for one of them with correct value and with a false one for the others (as there was actually no change for them).
The reason for that is the way you 'cache' the observables for the notifications - by UUID.
Thankfully …
> fix for invalid notifications for characteristics with the same UUID

- mockrxandroidble/src/main/java/com/polidea/rxandroidble/mockrxandroidble/RxBleClientMock.java
- mockrxandroidble/src/main/java/com/polidea/rxandroidble/mockrxandroidble/RxBleConnectionMock.java
- mockrxandroidble/src/main/java/com/polidea/rxandroidble/mockrxandroidble/RxBleDeviceMock.java
- mockrxandroidble/src/test/groovy/com/polidea/rxandroidble/mockrxandroidble/RxBleClientMockTest.groovy
I have a use-case where I need to simulate devices being discovered only after a certain time.
This PR adds a `RxBleClientMock#simulateDeviceDiscovery` method that can be used for this.
I'm relatively new to RxJava, but I'm hoping that the use of a `ReplaySubject` gives the same `scanBleDevices` behaviour as before. If there are better ways to do this, let me know :slightly_smiling_face: 
I also needed to make  `RxBleDeviceMock` and `RxBleConnectionMock` public in order to be able to create instances of those classes outside the `addDevice` method.
> On the fly mock device discovery

- mockrxandroidble/src/main/java/com/polidea/rxandroidble/mockrxandroidble/RxBleConnectionMock.java
The other variants of write writeCharacteristic are calling setValue to
change the internal value to this. In some of my tests, I was before
using the UUID version and was relying that setValue would be called acting
as a kind of holder for the read.
This assumption was broken with the writeCharacteristic variant that takes
a BluetoothGattCharacteristic and a byte array.
Resolved this minor thing by also calling setValue on the received
BluetoothGattCharacteristic.
> Fixed connection mock direct writeCharacteristic not callind setValue

- mockrxandroidble/src/main/java/com/polidea/rxandroidble/mockrxandroidble/RxBleConnectionMock.java
- mockrxandroidble/src/main/java/com/polidea/rxandroidble/mockrxandroidble/RxBleDeviceMock.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/RxBleClientImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/RxBleConnection.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/RxBleRadioOperationCustom.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/RxBleRadio.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/RxBleRadioOperation.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/LongWriteOperationBuilderImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/RxBleConnectionImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/operations/RxBleRadioOperationCharacteristicLongWrite.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/radio/RxBleRadioImpl.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/FlatRxBleRadio.groovy
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/RxBleClientTest.groovy
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/connection/RxBleConnectionTest.groovy
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/radio/RxBleRadioTest.groovy
- sample/src/main/java/com/polidea/rxandroidble/sample/example6_custom_operation/CustomOperationExampleActivity.java
- sample/src/main/res/layout/activity_example6.xml
The RxBleConnection interface has now a new method named queue that enable
library consumer to queue their own RxBleOperation. The queue method
receives in parameter a builder function taking three arguments. In order,
the RxBleRadio scheduler (not required to be used), the BluetoothGatt object
to interact with Android BLE API and RxBleGattCallback to receive Android
BLE API callbacks.
The builder parameter should return a concrete implementation of
RxBleOperation that will be executed as part of normal RxBleRadio operation.
This custom RxBleOperation must respect the RxBleOperation contract by
releasing the semaphore, otherwise, queue will be stuck forever.
This feature shall be used only by people that studied the RxAndroidBLE
source code and understand the implication of running their …
> Added a way to execute custom RxBleRadioOperation

- rxandroidble/src/main/java/com/polidea/rxandroidble/RxBleClientImpl.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/RxBleClientTest.groovy
Fixes scan never getting started when retrying on failed scan operation
>  Fixes issue #175 retrying on Scan operation on error

- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/util/UUIDUtil.java
Android Studio, while using Kotlin, was complaining that couldn't initialize the `UUIDUtil` class because the constructor wasn't `public`.
> Makes UUIDUtil constructor public to solve Kotlin problem

- README.md
Recently it seems like google has started checking for duplicate permissions in the play store. resulting in some issues when uploading:
https://stackoverflow.com/questions/44299197/google-play-apk-upload-error-duplicate-declarations-of-permission
Add some documentation to state that RxAndroidBle handles permissions for you and how to handle it if you need ACCESS_COARSE_LOCATION on versions < 23
> Address possible permission issues in docs

- CHANGELOG.md
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/NotificationAndIndicationManager.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/connection/NotificationAndIndicationManagerTest.groovy
Related to #231 
Until now the `Observable<byte[]>` emitted from `RxBleConnection.setupNotification()`/`RxBleConnection.setupIndication()` did not complete when the `RxBleConnection.setupNotification()`/`RxBleConnection.setupIndication()` was unsubscribed and notification/indication was teardown. Additionally the `Observable<byte[]>` did not propagate errors when the `RxBleConnection` has disconnected. This behaviour is fixed with this Pull Request.
> Fix notify/indicate observable termination

- CHANGELOG.md
- rxandroidble/src/main/java/com/polidea/rxandroidble/exceptions/BleCannotSetCharacteristicNotificationException.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/NotificationAndIndicationManager.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/connection/NotificationAndIndicationManagerTest.groovy
https://github.com/Polidea/RxAndroidBle/issues/225
Notification setup `Observable<Observable<byte[]>>` is now observing disconnection events to better notify about exceptions. Added cause to `BleCannotSetCharacteristicNotificationException` where possible.
> Fixed `NotificationAndIndicationManager` error handling.

- CHANGELOG.md
- rxandroidble/src/main/java/com/polidea/rxandroidble/RxBleConnection.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/RxBleDevice.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/DeviceModule.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/DeviceModuleBinder.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/RxBleDeviceImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/ConnectionModule.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/ConnectionStateChangeListener.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/Connector.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/ConnectorImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/operations/RxBleRadioOperationConnect.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/operations/RxBleRadioOperationDisconnect.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/RxBleDeviceTest.groovy
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/connection/ConnectorImplTest.groovy
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/operations/RxBleRadioOperationConnectTest.groovy
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/operations/RxBleRadioOperationDisconnectTest.groovy
https://github.com/Polidea/RxAndroidBle/issues/50
Previously `RxBleDevice.observeConnectionStateChanges()` was emitting immediately the initial state. The state was derived from user’s actions (i.e. `CONNECTING` was emitted right after user has subscribed to `RxBleDevice.establishConnection()`) rather than state in which the `BluetoothGatt` was. This behaviour has been changed to best reflect the state of `BluetoothGatt` at any given time.
> Adjusted `RxBleDevice.observeConnectionStateChanges()` behaviour

- CHANGELOG.md
- rxandroidble/src/main/java/com/polidea/rxandroidble/scan/ScanFilter.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/scan/ScanFilterTest.groovy
As it was observed for API <21 the name is not always available in the `ScanRecord` but it is available in the `BluetoothDevice`. On API >=21 this issue is not visible.
> Fixed scan filtering by name for API <21.

- CHANGELOG.md
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/RxBleRadioOperation.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/RxBleConnectionImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/operations/RxBleRadioOperationConnect.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/operations/RxBleRadioOperationDisconnect.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/util/RadioReleasingEmitterWrapper.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/MockOperation.groovy
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/connection/RxBleConnectionTest.groovy
https://github.com/Polidea/RxAndroidBle/issues/244
There was an issue (race condition) with releasing radio in `.onTerminate()` inside `RxBleRadioOperation.run()`. If the `Observable` called `.onNext()` and `.onCompleted()` in lines next to each other and user would use `observable.first()` then the `.onComplete()` may not be noticed by the `Subscriber` and `RadioReleaseInterface.release()` in `.onTerminate()` would not be called.
> Fix for radio not being released on operation complete.

- CHANGELOG.md
- README.md
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/RxBleLog.java
#Log messages can now be forwarded to crash reporting tools (crashlytics)
```java
RxBleLog.setLogger(new RxBleLog.Logger() {
@Override
public void log(final int level, final String tag, final String msg) {
Timber.tag(tag).log(level, msg);
}
});
```
> Allow usage of a custom logger (Timber) instead of Logcat

- rxandroidble/build.gradle
- rxandroidble/src/main/java/com/polidea/rxandroidble/ClientComponent.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/RxBleClientImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/RxBleRadioOperationCustom.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/RxBleConnectionImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/RxBleGattCallback.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/operations/OperationsProviderImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/operations/RxBleRadioOperationCharacteristicLongWrite.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/operations/RxBleRadioOperationDisconnect.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/radio/RxBleRadioImpl.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/RxBleClientTest.groovy
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/connection/RxBleConnectionTest.groovy
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/operations/RxBleRadioOperationDisconnectTest.groovy
Initially when working with the Android Bluetooth API (18 / Android 4.3) it was found that specific implementations (Samsung’s) cannot work correctly if called directly in callbacks from other calls. To mitigate the problem the next interaction was routed to Android main thread. Now when investigating the issue it turned out that it may be any other thread as long as it is not the callback thread.
> Thread calling the Native API changed from main to background.

- sample/src/main/res/values/strings.xml
Thank you this library!
I fix the following lint error.
```
String.format string doesn't match the XML format string
```
```
../../src/main/java/com/polidea/rxandroidble/sample/example5_rssi_periodic/RssiPeriodicExampleActivity.java:54: 
Suspicious argument type for formatting argument #1 in read_rssi: conversion is s, 
received int (argument #2 in method call) (Did you mean formatting character d, 'o' or x?)
```
> Fix lint error

- build.gradle
- rxandroidble/build.gradle
Thank you this repository!
android-apt is now available in the Android plugin.
ref. https://bitbucket.org/hvisser/android-apt/wiki/Migration
> Remove android-apt plugin

- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/operations/DisconnectOperation.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/operations/OperationDisconnectTest.groovy
In edge-case situations (like null `BluetoothGatt` or `BluetoothGattCallback.onConnectionStateChange()` reporting `status != GATT_SUCCESS`) the `ConnectionStateChangeListener` would not get called with state `DISCONNECTED`. In those situations there are no more fallbacks to do and apparently the best thing possible is to consider the connection disconnected.
> Fixed reporting `DISCONNECTED` (#273)

- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/DisconnectionRouter.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/RxBleConnectionConnectorImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/RxBleGattCallback.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/connection/DisconnectionRouterTest.groovy
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/connection/RxBleConnectionConnectorImplTest.groovy
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/connection/RxBleGattCallbackTest.groovy
`DeadObjectException` is usually thrown when interacting with `BluetoothAdapter` or `BluetoothGatt` instance that was obtained before bluetooth being turned off. Prior to library version `1.3.0` all errors raised when interacting with `BluetoothGatt` or recieved by `BluetoothGattCallback` were closing the connection (were emitted by `RxBleDevice.establishConnection()`). After `1.3.0` only errors raised in `RxBleRadioOperationConnect` and recieved by `BluetoothGattCallback.onConnectionStateChange()` were closing the connection so it was possible that `DeadObjectException`s raised repetedly by subscribing to i.e. `RxBleConnection.readRssi()` would not close the connection. Added monitoring of BluetoothAdapter’s state to prevent `DeadObjectException`s and inform the user about the connection …
> Added Bluetooth Adapter state monitoring to connection (#275)

- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/RxBleGattCallback.java
The hasObservers() method should check to see if the valueRelay or the errorRelay has observers instead of checking the valueRelay twice.
> Fix hasObservers conditional for Output class

- CHANGELOG.md
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/ConnectionComponent.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/ConnectionModule.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/ConnectionModuleBinder.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/ConnectionSubscriptionWatcher.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/ConnectorImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/DisconnectAction.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/MtuProvider.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/MtuWatcher.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/RxBleConnectionImpl.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/connection/ConnectorImplTest.groovy
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/connection/MtuWatcherTest.groovy
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/connection/RxBleConnectionTest.groovy
Previously the `RxBleConnection.currentMtu` was updated only when the MTU was updated by the central. This prevented Long Writes from utilising the increased Maximum Transfer Unit or the used from having a valid current MTU value—this made the utilisation of available bandwidth suboptimal.
> Fix MTU not updated when changed by the peripheral. (closes#293)

- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/ConnectionModuleBinder.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/DisconnectAction.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/DisconnectionRouter.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/DisconnectionRouterInput.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/DisconnectionRouterOutput.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/RxBleGattCallback.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/serialization/ConnectionOperationQueue.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/serialization/ConnectionOperationQueueImpl.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/DummyOperationQueue.groovy
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/connection/DisconnectionRouterTest.groovy
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/connection/RxBleGattCallbackTest.groovy
As long as the user is interested in the connection the `ConnectionOperationQueue` will check the `DisconnectionRouterOutput` for exceptions that cause disconnection. If this exception is emitted the `ConnectionOperationQueue` terminates itself with the emitted error. If the user unsubscribes from the `RxBleDevice.establishConnection()` then the `ConnectionOperationQueue` terminates itself with the `BleDisconnectedException` as it was before this change. Fixes #297
> Terminate ConnectionOperationQueue with proper exception

- .travis.yml
- build.gradle
- dependencies.gradle
- gradle/wrapper/gradle-wrapper.properties
- gradlew
- mockrxandroidble/build.gradle
- rxandroidble/build.gradle
- sample/build.gradle
> Update to Android Studio 3.0

- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/ConnectorImpl.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/connection/ConnectorImplTest.groovy
Without specifcation of `.subscribeOn()` and `.unsubscribeOn()` there was a possibility of a race condition when calling `.doOnSubscribe()` and `.doOnUnsubscribe()` which lead to calling `ConnectionOperationQueueImpl.onConnectionUnsubscribed()` before the `.onConnectionSubscribed()` has returned leading to a `NullPointerException`. By default `.doOnSubscribe()` is called on a thread that calls `.subscribe()` and `.doOnUnsubcribe()` is called on thread that calls `Subscription.unsubscribe()`.
> Call ConnectionSubscriptionWatcher on Bluetooth Callbacks Scheduler (fixes #308)

- README.md
New description better matches the original purpose of “MockRxAndroidBle” module. It also now gives a better solution for unit testing.
> Changed “Unit testing” paragraph of Readme.

- CHANGELOG.md
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/DisconnectionRouter.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/connection/DisconnectionRouterTest.groovy
DisconnectionRouter was subscribing to adapterStateObservable which uses `BroadcastReceiver` on a `Context` internally. The adapterStateObservable should be unsubscribed as soon as disconnection happens. It was not the case due to lack of `.first()` operator.
> Fixes DisconnectionRouter leaking subscription

- CHANGELOG.md
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/operations/OperationsProviderImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/operations/ServiceDiscoveryOperation.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/util/RxBleServicesLogger.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/utils/StandardUUIDsParser.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/operations/OperationServicesDiscoverTest.groovy
- sample/src/main/java/com/polidea/rxandroidble/sample/SampleApplication.java
Extended logger for the peripheral GATT content. If the logger is set to verbose then structure of the:
- services
- characteristics
- descriptors
is printed in logs.
Example output:
```
--------------- ====== Printing peripheral content ====== ---------------
PERIPHERAL ADDRESS: 00:08:7B:00:BB:84
PERIPHERAL NAME: Some device
-------------------------------------------------------------------------
Primary Service - Generic Access (00001800-0000-1000-8000-00805f9b34fb)
Instance ID: 1
-> Characteristics:
* Device Name (00002a00-0000-1000-8000-00805f9b34fb)
Properties: [ READ ]
* Appearance (00002a01-0000-1000-8000-00805f9b34fb)
Properties: [ READ ]
* Peripheral Privacy Flag (00002a02-0000-1000-8000-00805f9b34fb)
Properties: [ READ WRITE ]
* Peripheral Preferred Connection Parameters …
```
> Verbose logging of the peripheral GATT server content

- rxandroidble/src/main/java/com/polidea/rxandroidble/RxBleDevice.java
`RxBleDevice.observeConnectionStateChanges()` function not meant to be used as a reconnection logic trigger. It is only a convenience function for using in the UI.
Connected to #264
> Added a usage hint to device’s observe state function

- sample/src/main/java/com/polidea/rxandroidble2/sample/example1_scanning/ScanActivity.java
Fix for issue #407 . Disable RecyclerView animations messing up screen when user scrolls through long device list during scan.
> Removed animation from sample scanning result list

- rxandroidble/src/main/java/com/polidea/rxandroidble2/RxBleConnection.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/connection/RxBleConnectionImpl.java
> Add possibility to modify custom operation priority #412

- mockrxandroidble/src/main/java/com/polidea/rxandroidble2/mockrxandroidble/RxBleConnectionMock.java
Mock module wouldn't build since the interface changed with #414 is not implemented there
> Fix build broken by #414 by adding missing implementation

- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/serialization/FIFORunnableEntry.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/internal/serialization/FIFORunnableEntryTest.groovy
As reported we should release the semaphore when we don't execute the operation.
Fixes #426
> Fix deadlock reported by #426 when FIFORunnable is disposed before running

- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/util/LocationServicesOkObservableApi23.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/internal/util/LocationServicesOkObservableApi23Test.groovy
Would happen on a 6P when toggling bluetooth on and off. This will make sure that we do always register before we unregister.
> Fixes crash due to `Receiver not registered`

- rxandroidble/src/main/java/com/polidea/rxandroidble2/exceptions/BleAdapterDisabledException.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/exceptions/BleDisconnectedException.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/exceptions/BleGattException.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/SingleResponseOperation.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/connection/DisconnectionRouter.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/connection/RxBleConnectionImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/connection/RxBleGattCallback.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/operations/CharacteristicLongWriteOperation.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/operations/ConnectOperation.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/operations/DisconnectOperation.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/serialization/ConnectionOperationQueueImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/utils/GattStatusParser.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/exceptions/BleDisconnectedExceptionTest.groovy
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/exceptions/BleGattExceptionTest.groovy
- Added GATT status to description mapping
Fixes #282
> Added GATT status code to a BleDisconnectException

- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/connection/DisconnectionRouter.java
DisconnectionRouter is storing emitters waiting for information about disconnection in a Queue. This Queue may be accessed concurrently and it was not prepared for this scenario. Additionally there could be a race if an exception would happen when a new emitter would get subscribed.
Fixes #441
> Prepare DisconnectionRouter for concurrent access.

- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/operations/CharacteristicLongWriteOperation.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/internal/operations/OperationCharacteristicLongWriteTest.groovy
It was susceptible to a race condition due to a repetition observable using `.takeUntil()` which emits a value before checking the complete condition. This could lead to an excess characteristic write being executed that was not secured on a connection queue leading to next operation being rejected.
Fixes #463
> Fixed CharacteristicLongWriteOperation repetition logic

- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/scan/BackgroundScannerImpl.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/internal/scan/BackgroundScannerTest.groovy
> Fixed NPE when calling BackgroundScanner while BT is OFF

- rxandroidble/src/main/java/com/polidea/rxandroidble2/NotificationSetupMode.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/connection/NotificationAndIndicationManager.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/internal/connection/NotificationAndIndicationManagerTest.groovy
Some BLE peripherals are starting to notify right after the Command Characteristic Config Descriptor is written with ENABLE_NOTIFICATION value. In this case the DEFAULT notification setup mode could miss the first notifications before the downstream would subscribe. QUICK_SETUP mitigates this problem by postponing the write of Command Characteristic Config Descriptor until at least one observer has subscribed.
Parent `Observable<Observable<byte[]>>` emits an error if the scheduled CCC descriptor write fails and emitted child `Observable<byte[]>` completes. 
Connected to #195
> Added notification quick setup mode

- rxandroidble/src/main/java/com/polidea/rxandroidble/NotificationSetupMode.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/NotificationAndIndicationManager.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/connection/NotificationAndIndicationManagerTest.groovy
Some BLE peripherals are starting to notify right after the Command Characteristic Config Descriptor is written with ENABLE_NOTIFICATION value. In this case the DEFAULT notification setup mode could miss the first notifications before the downstream would subscribe. QUICK_SETUP mitigates this problem by postponing the write of Command Characteristic Config Descriptor until at least one observer has subscribed.
Parent Observable<Observable<byte[]>> emits an error if the scheduled CCC descriptor write fails and emitted child Observable<byte[]> completes.
> Added notification quick setup mode (RxJava1)

- mockrxandroidble/src/main/java/com/polidea/rxandroidble2/mockrxandroidble/RxBleClientMock.java
This adds an overload of `CharacteristicBuilder.addCharacteristic()` method which can take an additional parameter to set the properties of a characteristic.
This is intended to make possible testing of scenarios where the properties of a characteristic are checked by code under test. 
Concrete use case is me working on a PR adding unit tests for the `Presenter` class in the advanced characteristic example in the RxAndroidBle sample app.
> [Mock] add possibility to set properties of a characteristic

- dependencies.gradle
`compileSdkVersion` in all modules is `28`, yet the support lib version was `27.1.0`.
This PR updates support lib version to `28.0.0`.
> [fix] bump support library version to 28.0.0

- sample/build.gradle
- sample/src/main/java/com/polidea/rxandroidble2/sample/example1_scanning/ScanActivity.java
- sample/src/main/java/com/polidea/rxandroidble2/sample/example1a_background_scanning/BackgroundScanActivity.java
- sample/src/main/java/com/polidea/rxandroidble2/sample/example2_connection/ConnectionExampleActivity.java
- sample/src/main/java/com/polidea/rxandroidble2/sample/example3_discovery/ServiceDiscoveryExampleActivity.java
- sample/src/main/java/com/polidea/rxandroidble2/sample/example4_characteristic/CharacteristicOperationExampleActivity.java
- sample/src/main/java/com/polidea/rxandroidble2/sample/example4_characteristic/advanced/AdvancedCharacteristicOperationExampleActivity.java
- sample/src/main/java/com/polidea/rxandroidble2/sample/example5_rssi_periodic/RssiPeriodicExampleActivity.java
- sample/src/main/java/com/polidea/rxandroidble2/sample/example7_long_write/LongWriteExampleActivity.java
Removes `rxlifecycle` based Disposable handling, leaving only explicit handling in `onPause()`/`onDestroy()`.
Also adds missing `SDK` version check for background scanning calls.
> [sample] disposable handling

- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/connection/ConnectorImpl.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/internal/connection/ConnectorImplTest.groovy
There was a race condition in ConnectorImpl which was simultaneously scheduling connecting operation and observing BT adapter being switched off. As the client operation queue runs on it’s own thread it was possible that the connecting operation would get scheduled and started but cancelled before the actual `protectedRun()` would get executed — this result in a situation where the client queue would get blocked and never released due to the operation never being run but still responsible for releasing.
Workaround: start observing BT adapter state after the connecting operation finishes. The operation is observing it either way during the execution and will emit an error if BT is off
Fixes #516
> Fixed stalled client queue when adapter is off

- rxandroidble/src/main/java/com/polidea/rxandroidble2/RxBleClientImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/scan/ExternalScanSettingsExtension.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/scan/ScanPreconditionsVerifier.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/scan/ScanPreconditionsVerifierApi18.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/scan/ScanPreconditionsVerifierApi24.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/scan/ScanSettings.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/RxBleClientTest.groovy
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/internal/scan/ScanPreconditionsVerifierApi18Test.groovy
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/internal/scan/ScanPreconditionsVerifierApi24Test.groovy
Some Android devices are not returning any results if Location Providers (Location Services) are turned off. The library defaults to check if Location Services are turned on before the scan and emitting an exception if not so the user would get a clear information what they may expect. However now the user may start handling this on their own by switching off the check.
Fixes #106
> Added option to disable Location Providers check before scan

- sample-kotlin/src/main/kotlin/com/polidea/rxandroidble2/samplekotlin/example1_scanning/ScanActivity.kt
- sample-kotlin/src/main/kotlin/com/polidea/rxandroidble2/samplekotlin/example1a_background_scanning/BackgroundScanActivity.kt
- sample-kotlin/src/main/kotlin/com/polidea/rxandroidble2/samplekotlin/util/LocationPermission.kt
- sample/src/main/java/com/polidea/rxandroidble2/sample/example1_scanning/ScanActivity.java
- sample/src/main/java/com/polidea/rxandroidble2/sample/example1a_background_scanning/BackgroundScanActivity.java
- sample/src/main/java/com/polidea/rxandroidble2/sample/util/LocationPermission.java
On Android API < 23 (tested on API 19) `ContextCompat.checkSelfPermission(Context, android.Manifest.permission.ACCESS_COARSE_LOCATION)` returns `PackageManager.PERMISSION_DENIED` where it is not needed to perform a successful BLE scan. Do not call `ContextCompat.checkSelfPermission` in this case.
> Fixed Location Permission check for OS API < 23

- README.md
It should be now easier for the users to discover classes that could potentially help them with development (i.e. ConnectionSharingAdapter which is now deprecated but points to RxReplayingShare)
Connected to #541
> Added reference to ‘utils’ package in Readme

- rxandroidble/src/main/java/com/polidea/rxandroidble2/RxBleDevice.java
It is now reflecting the actual behaviour of the library.
Fixes #557
> Fixed Javadoc of connecting with timeout function

- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/util/ClientStateObservable.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/internal/util/ClientStateObservableTest.groovy
Android BluetoothAdapter has 4 states. ON, OFF, TURNING_ON, TURNING_OFF. Any state other than ON evaluates to BLUETOOTH_NOT_ENABLED. For instance when the state observing starts in OFF state and adapter is turned on then a TURNING_ON state is emitted but it is not a change from the subscriber’s perspective.
Fixes #555
> Fixed RxBleClient.observeStateChanges() emitting while turning BT on

- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/util/LocationServicesOkObservableApi23Factory.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/internal/util/LocationServicesOkObservableApi23FactoryTest.groovy
Due to a race condition with subscribing/unsubscribing from different threads it may have happened that unregistering was made before registering finished resulting in an exception being thrown.
Fixes #572
> Fixed IllegalArgumentException in LocationServicesOkObservableApi23Factory

- rxandroidble/src/main/java/com/polidea/rxandroidble2/RxBleAdapterStateObservable.java
The issue was hidden by a try/catch. This should not happen when using Schedulers.trampoline() to subscribe/unsubscribe.
> Fixed BroadcastReceiver leak in RxBleAdapterStateObservable

- rxandroidble/src/main/java/com/polidea/rxandroidble2/LogOptions.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/RxBleClient.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/RxBleClientImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/RxBleLog.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/logger/LoggerSetup.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/operations/ScanOperationApi18.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/operations/ScanOperationApi21.java
Usually there are a lot of peripherals advertising nearby and it may be considered too spammy.
Closes #577
> Added possibility to disable scanned peripherals logging

- .buildscript/deploy_snapshot.sh
- gradle.properties
Only versions named ‘*-SNAPSHOT’ should be released as such.
> Added version name check in snapshot deployment script

- rxandroidble/src/main/java/com/polidea/rxandroidble2/RxBleAdapterStateObservable.java
Setting a cancelable on an `Emitter` did run it immediately if it was already disposed. Postponing the setting until after the `BroadcastReceiver` is registered fixed the issue.
Fixes #592
> Fixed IllegalStateException on RxBleAdapterStateObservable

- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/operations/LegacyScanOperation.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/operations/ScanOperation.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/operations/ScanOperationApi18.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/operations/ScanOperationApi21.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/internal/operations/OperationScanApi21Test.groovy
Hi,
I'm submitting this pull request because I'm receiving too many crashes from my application. 
> Fatal Exception: io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | com.polidea.rxandroidble2.exceptions.BleScanException: Scan failed because application registration failed (code 6)
at io.reactivex.plugins.RxJavaPlugins.onError + 367(RxJavaPlugins.java:367)
at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError + 73(ObservableCreate.java:73)
at com.polidea.rxandroidble2.internal.operations.ScanOperationApi21$1.onSca …
> UndeliverableException in ScanOperationApi21

- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/scan/ExternalScanSettingsExtension.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/scan/ScanSetupBuilderImplApi23.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/scan/ScanSettings.java
Android API may be requested to match first or the last appearance of peripherals. When `ScanFilter`s are not specified or they are empty (match all advertisements) — the hardware/offloaded filtering will likely overwhelm the BT chip — this is why scan is not started with `SCAN_FAILED_FEATURE_UNSUPPORTED` or `SCAN_FAILED_OUT_OF_HARDWARE_RESOURCES` error in the result.
This commit adds a workaround by falling back to emulated callback type in the described scenario — similarly as it is working on API 21 and API 18.
Closes #561
> Workaround scan failure for non-default callback type and empty filters

- .gitattributes
Git may automatically convert line endings to those used by the host system (CRLF on Windows, LF otherwise). This proved to be an issue for developers checking out the repository on Windows machines where `checkstyle` plugin would complain that some lines are too long because the EOL marker is longer. This `.gitattributes` file should make git always set the EOL marker to LF.
Fixes #567
> Fixed changing EOL markers on checkout

- rxandroidble/src/main/java/com/polidea/rxandroidble2/exceptions/BleCharacteristicNotFoundException.java
This includes deprecating an accessor and creating a new one.
> Fixed typo in BleCharacteristicNotFoundException

- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/internal/connection/DisconnectionRouterTest.groovy
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/internal/connection/RxBleGattCallbackTest.groovy
Due to lack of configuration of two tests a following warning was logged:
```
WARNING: No manifest file found at ./AndroidManifest.xml.
Falling back to the Android OS resources only.
To remove this warning, annotate your test class with @Config(manifest=Config.NONE).
No such manifest file: ./AndroidManifest.xml
```
> Fixed ElectricSpecification tests warning

- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/connection/RxBleGattCallback.java
Due to a copy-paste error it logged “onMtuChanged” instead of “onReadRemoteRssi”
> Fixed BluetoothGattCallback.onReadRemoteRssi log

- rxandroidble/build.gradle
- rxandroidble/proguard-rules.pro
Proguard by default removes unused code. BluetoothGattCallback.onConnectionUpdated() function is hidden in AOSP and therefore Proguard removes the callback. Added a correct consumer Proguard configuration to the library package so the callback will not be renamed/removed.
> Fixed connection update not working in obfuscated applications

- CHANGELOG.md
- rxandroidble/src/main/AndroidManifest.xml
- rxandroidble/src/main/java/com/polidea/rxandroidble2/ClientComponent.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/exceptions/BleScanException.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/util/CheckerLocationPermission.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/util/LocationServicesStatusApi23.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/internal/util/LocationServicesStatusApi23Test.groovy
Since Android 10 ‘Manifest.permission.ACCESS_COARSE_LOCATION’ is no longer sufficient to get BLE scan results. ‘Manifest.permission.ACCESS_FINE_LOCATION’ is a must. Adjusted BleScanException.LOCATION_PERMISSION_MISSING javadoc to reflect that.
Closes #637
> Fixed location permission check for Android 10

- README.md
It now has info about what runtime permissions are needed on different API levels.
Related to #637
> Improved Permissions paragraph of Readme

- dagger-compiler-shadow/build.gradle
- dagger-library-shadow/build.gradle
Hi
This commit fixes some ordering violations in build script. Specifically, the task `shadowJar` of the subproject `dagger-library-shadow` must run after the task `jar`, because the name of the generated shadow jar (`dagger-library-shadow-1.10.4-SNAPSHOT.jar`) conflicts with that generated by the naive jar task.
As a result, the contents of the jar file might be different depending on the order in which gradle runs task. For example this is the correct contents of the jar `dagger-library-shadow-1.10.4-SNAPSHOT.jar` (when the task `shadowJar` is executed after `jar`).
```
META-INF/
META-INF/MANIFEST.MF
bleshadow/
bleshadow/dagger/
bleshadow/dagger/Binds.class
bleshadow/dagger/BindsInstance.class
bleshadow/dagger/BindsOptionalOf.class
bleshadow/dagger/Component$Builder.class …
```
> Bugfix: Fix race condition regarding shadow jar

- rxandroidble/src/main/java/com/polidea/rxandroidble2/ClientComponent.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/connection/RxBleGattCallback.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/serialization/RxBleThreadFactory.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/internal/connection/RxBleGattCallbackTest.groovy
Having several observers on a specific, single threaded scheduler and several subsequent emissions from another thread the scheduler distributes events sequentially between observers. The non-intuitive part is that it first distributes all events to the first observer, then all events to the second and so on… This may end up with observers being notified about events in a wrong order. See https://github.com/ReactiveX/RxJava/issues/6696
Fixes #628
> Fixed possibly incorrect order of emissions from RxBleGattCallback

- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/serialization/FIFORunnableEntry.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/internal/serialization/FIFORunnableEntryTest.groovy
`.subscribeOn()` operator seems to be not actually subscribing to the upstream if downstream is already disposed. It seems impossible to track whether the upstream was subscribed or not and therefore side-effects for releasing a queue cannot be reliably run. Getting rid of the operator but running the subscription on the `Scheduler`’s worker directly makes the operation being always run. It’s the operation’s responsibility to release the queue at a proper moment (when the `BluetoothGatt` is no longer blocked).
Fixes #644
> Fixes stalled operation queue in a rare race situation

- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/util/RxBleAdapterWrapper.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/internal/util/RxBleAdapterWrapperTest.groovy
Apparently on some versions of Android OS it is possible to get BluetoothLeScanner even if bluetooth is off. In this situation calling any methods/functions on the scanner will fail with an IllegalStateException due to adapter being off. Previously the scanner was not possible to obtain when the adapter was off or the exception was not thrown.
Fixes #648
> Added check BluetoothAdapter.isEnabled() before calling BluetoothLeScanner.stopScan(ScanCallback)

- README.md
It was a leftover from RxJava 1 times.
Fixes #674
> Fixed Combined Read and Write snippet

- mockrxandroidble/src/main/java/com/polidea/rxandroidble2/mockrxandroidble/RxBleClientMock.java
- mockrxandroidble/src/main/java/com/polidea/rxandroidble2/mockrxandroidble/RxBleDeviceMock.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/connection/DisconnectionRouter.java
This PR adds support for mocking/adding a `BluetoothDevice` to the `RxBleDeviceMock` via the method `.bluetoothDevice()` in the builder.
> Added support for BluetoothDevice

- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/logger/LoggerUtil.java
This situation seems to happen when a characteristic is first read with a non-success status.
Fixes #678
> Fixed logging attributes with null value

- mockrxandroidble/src/main/java/com/polidea/rxandroidble2/mockrxandroidble/RxBleScanRecordMock.java
- mockrxandroidble/src/main/java/com/polidea/rxandroidble2/mockrxandroidble/internal/ScanRecordDataConstructor.java
- mockrxandroidble/src/test/groovy/com/polidea/rxandroidble2/mockrxandroidble/RxBleClientMockLegacyTest.groovy
- mockrxandroidble/src/test/groovy/com/polidea/rxandroidble2/mockrxandroidble/RxBleClientMockTest.groovy
- mockrxandroidble/src/test/groovy/com/polidea/rxandroidble2/mockrxandroidble/RxBleConnectionMockTest.groovy
- mockrxandroidble/src/test/groovy/com/polidea/rxandroidble2/mockrxandroidble/internal/ScanRecordDataConstructorTest.groovy
Based on https://github.com/Polidea/RxAndroidBle/pull/707.
Implements construction of the mock scan record's bytes
> Construct scanrecord bytes

- mockrxandroidble/src/main/java/com/polidea/rxandroidble2/mockrxandroidble/RxBleConnectionMock.java
The object passed into these maps is the same as returned from them
> Remove maps which are redundant

- mockrxandroidble/src/main/java/com/polidea/rxandroidble2/mockrxandroidble/RxBleClientMock.java
The previous code would block forever unless the subject contained a matching mock device. This takes a snapshot of the current values in the subject and looks for a match instead.
> Fix for when no devices match MAC

- mockrxandroidble/build.gradle
To be able to verify that tests were properly run on CI. There was once a time when tests were broken and despite the task being executed no actual tests were run. This change will help pinpoint the same problem if it would ever occur.
> mockclient tests output to console

- mockrxandroidble/src/main/java/com/polidea/rxandroidble2/mockrxandroidble/RxBleClientMock.java
RxBleClientMock.getState() returns State.READY and observeStateChanges() emits State.READY again as a change were there is no change in reality. Fixed by making observeStateChanges() emitting nothing.
Fixes #738
> Fixed RxBleClientMock.observeStateChanges() output

- rxandroidble/src/main/java/com/polidea/rxandroidble2/RxBleDevice.java
Before this change, it was not clear that you would get a disconnected exception when you had set autoConnect to true and the user turned off the BLE adapter. This was confusing to me until I read the source for DisconnectionRouter.
> Improve javadocs about BleDisconnectedException

- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/util/CheckerLocationProvider.java
It turned out that Settings.Secure.LOCATION_MODE has been deprecated and a new API in LocationManager was introduced.
> Added a new location check for API 28+.

- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/util/LocationServicesStatusApi23.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/internal/util/LocationServicesStatusApi23Test.groovy
Apparently on >= API 29 Android will require location to be turned on irregardless of the target SDK for the application to return scan results. Prior to API 29 it was a common workaround to use target SDK of 21 so the user will not be prompted to give location permissions and no need for location being turned on by the user to scan for BLE peripherals.
Fixes #742
> Fixed requirements for location services check.

- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/scan/AndroidScanObjectsConverter.java
Apparently API 31 (S) does check for null MAC address when specifying a ScanFilter.
This fix will likely be obsolete on some next version of the Android 12 when it will be available for tests.
Closes #749
> Added conditional MAC address setting

- README.md
- mockrxandroidble/build.gradle
- rxandroidble/build.gradle
- rxandroidble/src/main/AndroidManifest.xml
- rxandroidble/src/main/java/com/polidea/rxandroidble2/ClientComponent.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/RxBleClient.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/RxBleClientImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/util/CheckerScanPermission.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/util/LocationServicesStatusApi23.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/util/LocationServicesStatusApi31.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/RxBleClientTest.groovy
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/internal/util/CheckerScanPermissionTest.groovy
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/internal/util/LocationServicesStatusApi23Test.groovy
- sample-kotlin/build.gradle
- sample-kotlin/src/main/AndroidManifest.xml
- sample/build.gradle
- sample/src/main/AndroidManifest.xml
API 31 introduces new Bluetooth permissions required for BLE operations. In the context of RxAndroidBle the important ones are:
- `BLUETOOTH_SCAN` — replaces previously needed ACCESS_FINE_LOCATION
- `BLUETOOTH_CONNECT` — a new concept
Considerations:
The library's AndroidManifest.xml does include `ACCESS_COARSE_LOCATION` and `ACCESS_FINE_LOCATION` since API 23. Technically these could be restricted to `maxSdkVersion="30"` but it could be a breaking change for apps that require location access otherwise. There is a new example in the Readme if the user does not want to require location access for other reasons than scanning BLE peripherals.
TODO:
Result: If the user sets flag `neverForLocation` then Location Services are not needed. Otherwise they still are needed to get scan results. …
> WIP: Support API 31 (Android 12) new Bluetooth permissions

- README.md
I've re-written the permissions section to focus on what the user needs to do to implement the correct permissions in their App for their use case.
> Rewrite permissions section of README

- rxandroidble/build.gradle
Dagger in 2.25.4 introduced a tracking file ('META-INF/com.google.dagger_dagger.version') which is published with the archive. If the file is in a library and the app also uses Dagger it can break a build by default because the file is already there.
Fixes #789
> Fixed build for apps using Dagger

- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/util/CheckerPermission.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/internal/util/CheckerPermissionTest.groovy
- rxandroidble/src/test/java/android/content/Context.java
The cache should help with much more frequent permission checks in case of using `RxBleDevice#toString()`. After the permission is granted no more calls to `Context#checkPermission(String, int, int)` will be made until the client is recreated.
> Added granted permissions cache in CheckerPermission.

- rxandroidble/src/main/java/com/polidea/rxandroidble2/RxBleClient.java
Mentioning new requirements for Android 12 / API >= 31.
Closes #788
> Updated RxBleClient#getBondedDevices() javadoc.

- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/scan/AndroidScanObjectsConverter.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/scan/ScanSettings.java
This option allows for scanning of BLE devices with extended advertising.
It is supported on Android 8.0 and above.
https://developer.android.com/reference/android/bluetooth/le/ScanSettings.Builder#setLegacy(boolean)
Closes #774
> ScanSettings: Add setLegacy method

- rxandroidble/src/main/java/com/polidea/rxandroidble2/RxBleConnection.java
Hello @dariuszseweryn,
since Android 13 the real maximal supported MTU by Android is 515.
Even though in Android source code the [GATT_MAX_MTU_SIZE](https://cs.android.com/android/platform/superproject/+/master:packages/modules/Bluetooth/system/stack/include/gatt_api.h;l=244;drc=1918034a0730839c7a07b1260b1ab74b80d6b4e6) is still set to 517, the data buffer size [GAT_MAX_ATTR_LEN](https://cs.android.com/android/platform/superproject/+/master:packages/modules/Bluetooth/system/stack/include/gatt_api.h;l=250;drc=1918034a0730839c7a07b1260b1ab74b80d6b4e6;bpv=1;bpt=1) is now capped at 512 bytes.
It leads to the situation when Android allows you to negotiate MTU 517, [but it drops all the packets with data larger then 512 bytes](https://cs.android.com/android/platform/superproject/+/master:package …
> Fix maximal supported MTU on Android 13

- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/RxBleLog.java
> Fixed tag message generation with Proguard use

- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/connection/ConnectionComponent.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/connection/ConnectionModule.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/connection/MtuBasedPayloadSizeLimit.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/internal/connection/MtuBasedPayloadSizeLimitTest.groovy
On Android 13 when negotiated MTU > 515, CharacteristicLongWriteOperation would by default split data into chunks that did not fit Android internal data buffer for BLE writes. Reason for that is that on Android 13 the maximum attribute data buffer length was reduced from 600 to 512 bytes - which is now according to BLE Specs. Android 14 makes MTU negotiation to the maximum supported value on Android (517) by default, making this problem more likely to surface.
Fixes #843
> Fixed CharacteristicLongWriteOperation defaults

- mockrxandroidble/src/main/java/com/polidea/rxandroidble2/mockrxandroidble/RxBleClientMock.java
- mockrxandroidble/src/main/java/com/polidea/rxandroidble2/mockrxandroidble/RxBleScanResultMock.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/ClientComponent.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/ScanResultInterface.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/scan/AdvertisingSidExtractor.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/scan/AdvertisingSidExtractorApi18.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/scan/AdvertisingSidExtractorApi26.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/scan/InternalScanResultCreator.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/scan/InternalToExternalScanResultConverter.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/scan/RxBleInternalScanResult.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/scan/ScanSettingsEmulator.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/scan/ScanResult.java
Add `advertisingSid` property to `ScanResult`.
Fixes #854
> Add `advertisingSid` property to `ScanResult`
