dariuszseweryn/RxAndroidBle

- README.md
Kind folk from the chat noticed that, kudos to him.
> Fixed missing parenthesis in README.md

- sample/src/main/java/com/polidea/rxandroidble/sample/example4_characteristic/CharacteristicOperationExampleActivity.java
The updateUI method was being called before the connection
was established.
> Sample: Fix CharacteristicOperationExample not updating UI

- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/NotificationAndIndicationManager.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/util/ActiveCharacteristicNotification.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/internal/connection/NotificationAndIndicationManagerTest.groovy
Simplified the implementation. Less LOC, less instantiations, less method count, less fields, more clarity.
> Refactored `NotificationAndIndicationManager`

- rxandroidble/src/main/java/com/polidea/rxandroidble/RxBleDevice.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/RxBleDeviceImpl.java
It may be undefined as it's an optional broadcast parameter.
This fixes issue #263.
> Added @Nullable annotation to a bluetooth device name. 

- README.md
> Added Hot/Cold type to Observable behaviour in Readme

- .gitignore
I think it may have sense. Feel free to comment if it should not be ignored.
> Added dagger shadows to gitignore.

- mockrxandroidble/build.gradle
- rxandroidble/build.gradle
Failing tests are expected. Need to fix in a separate commit.
Fixes #411
> Fixed command line tests execution.

- README.md
Started a Wiki as well.
Closes #383
> Added FAQ: UndeliverableException reference

- rxandroidble/src/main/java/com/polidea/rxandroidble/exceptions/BleAdapterDisabledException.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/exceptions/BleDisconnectedException.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/exceptions/BleGattException.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/SingleResponseOperation.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/DisconnectionRouter.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/RxBleConnectionImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/connection/RxBleGattCallback.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/operations/CharacteristicLongWriteOperation.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/operations/ConnectOperation.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/operations/DisconnectOperation.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/internal/serialization/ConnectionOperationQueueImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble/utils/GattStatusParser.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/exceptions/BleDisconnectedExceptionTest.groovy
- rxandroidble/src/test/groovy/com/polidea/rxandroidble/exceptions/BleGattExceptionTest.groovy
Backported from #405 to rxjava1 version of a library.
> Added GATT status code to BleDisconnectException (#405)

- sample/src/main/java/com/polidea/rxandroidble2/sample/SampleApplication.java
More info: https://github.com/Polidea/RxAndroidBle/wiki/FAQ:-UndeliverableException
> Added RxJavaPlugins error handler

- sample-kotlin/src/main/AndroidManifest.xml
- sample-kotlin/src/main/kotlin/com/polidea/rxandroidble2/samplekotlin/DeviceActivity.kt
- sample-kotlin/src/main/kotlin/com/polidea/rxandroidble2/samplekotlin/example1_scanning/ScanActivity.kt
- sample-kotlin/src/main/kotlin/com/polidea/rxandroidble2/samplekotlin/example1a_background_scanning/BackgroundScanActivity.kt
- sample-kotlin/src/main/kotlin/com/polidea/rxandroidble2/samplekotlin/example1a_background_scanning/ScanReceiver.kt
- sample-kotlin/src/main/kotlin/com/polidea/rxandroidble2/samplekotlin/example3_discovery/ServiceDiscoveryExampleActivity.kt
- sample-kotlin/src/main/kotlin/com/polidea/rxandroidble2/samplekotlin/example4_characteristic/CharacteristicOperationExampleActivity.kt
- sample-kotlin/src/main/kotlin/com/polidea/rxandroidble2/samplekotlin/util/BluetoothGatt.kt
- sample-kotlin/src/main/kotlin/com/polidea/rxandroidble2/samplekotlin/util/ByteArray.kt
- sample-kotlin/src/main/kotlin/com/polidea/rxandroidble2/samplekotlin/util/LocationPermission.kt
- sample-kotlin/src/main/res/layout/activity_example1.xml
Adds `CharacteristicExampleActivity`.
This PR builds on top of #538 . Please merge it afterwards.
> [sample-kotlin] characteristic activity

- rxandroidble/src/main/java/com/polidea/rxandroidble2/utils/GattStatusParser.java
https://android.googlesource.com/platform/external/bluetooth/bluedroid/+/android-5.1.0_r1/stack/include/gatt_api.h
> Added more code descriptions from Android sources

- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/connection/DisconnectionRouter.java
Due to a race condition it was possible that when iterating through disconnection error subscribers one of them has unsubscribed resulting in a null reference. Now all of it should be handled by RxJava operator implementations.
Fixes #552
> Fixed NPE in DisconnectionRouter

- dependencies.gradle
- gradle.properties
- sample-kotlin/src/main/kotlin/com/polidea/rxandroidble2/samplekotlin/example4_characteristic/advanced/AdvancedCharacteristicOperationExampleActivity.kt
- sample/src/main/java/com/polidea/rxandroidble2/sample/example4_characteristic/advanced/AdvancedCharacteristicOperationExampleActivity.java
> Updated RxAndroid dependency to remove Jettifier

- rxandroidble/src/main/java/com/polidea/rxandroidble2/helpers/LocationServicesOkObservable.java
> Removed DisposableObserver wrapping in LocationServicesOkObservable

- .buildscript/deploy_snapshot.sh
It is now possible to set a whitelist of branches that may produce snapshots
> Reworked snapshot deploying script

- .buildscript/deploy_snapshot.sh
Use “true”/“false” and camelCase
> Make deploy_snapshot.sh consistent

- build.gradle
- dependencies.gradle
- gradle/gradle-mvn-push.gradle
- gradle/wrapper/gradle-wrapper.properties
- updated Gradle 4.10.1 => 5.1.1
- updated `com.github.johnrengelman.shadow` plugin to match Gradle 5.1
- updated `gradle-mvn-push.gradle` script to work with Gradle 5.1 and the shadow plugin
> Bumped gradle.

- checkstyle.gradle
> Bumped checkstyle plugin version

- rxandroidble/src/main/java/com/polidea/rxandroidble2/RxBleClientImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/RxBleDeviceServices.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/helpers/ByteArrayBatchObservable.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/RxBleDeviceImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/SingleResponseOperation.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/connection/ConnectorImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/connection/ServiceDiscoveryManager.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/operations/ConnectOperation.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/operations/ScanOperation.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/operations/ServiceDiscoveryOperation.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/scan/ScanSettingsEmulator.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/serialization/ClientOperationQueueImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/serialization/ConnectionOperationQueueImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/util/ByteAssociationUtil.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/util/QueueReleasingEmitterWrapper.java
Some are not used and marked by IDE as obsolete. Fixed them.
> Removed unneeded throw clauses

- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/operations/ConnectionPriorityChangeOperation.java
It returned wrong name of constant for `CONNECTION_PRIORITY_HIGH`
> Fixed ConnectionPriorityChangeOperation toString()

- .travis.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- mockrxandroidble/build.gradle
- rxandroidble/build.gradle
- sample-kotlin/build.gradle
- sample/build.gradle
Also updated groovy android gradle plugin, v2.0.1 fails on gradle 6
> Update gradle version

- build.gradle
- mockrxandroidble/src/main/java/com/polidea/rxandroidble2/mockrxandroidble/RxBleClientMock.java
- mockrxandroidble/src/main/java/com/polidea/rxandroidble2/mockrxandroidble/RxBleConnectionMock.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/RxBleClientImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/connection/DisconnectionRouter.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/connection/LongWriteOperationBuilderImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/connection/RxBleGattCallback.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/operations/LegacyScanOperation.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/scan/InternalScanResultCreator.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/util/CheckerLocationProvider.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/util/ObservableUtil.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/util/RxBleAdapterWrapper.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/util/UUIDUtil.java
- sample-kotlin/src/main/kotlin/com/polidea/rxandroidble2/samplekotlin/DeviceActivity.kt
- sample-kotlin/src/main/kotlin/com/polidea/rxandroidble2/samplekotlin/example2_connection/ConnectionExampleActivity.kt
- sample-kotlin/src/main/kotlin/com/polidea/rxandroidble2/samplekotlin/example3_discovery/ServiceDiscoveryExampleActivity.kt
- sample-kotlin/src/main/kotlin/com/polidea/rxandroidble2/samplekotlin/example4_characteristic/CharacteristicOperationExampleActivity.kt
- sample-kotlin/src/main/kotlin/com/polidea/rxandroidble2/samplekotlin/example4_characteristic/advanced/AdvancedCharacteristicOperationExampleActivity.kt
- sample-kotlin/src/main/kotlin/com/polidea/rxandroidble2/samplekotlin/example5_rssi_periodic/RssiPeriodicExampleActivity.kt
This pull request enabled unchecked and deprecation warnings and fixes these warnings in the project. However, I've been unable to suppress or fix the warnings for use of UUIDUtil in factories generated by Dagger.
> Warning fixes

- build.gradle
Gradle version update for Android Studio 4.1
> Gradle update

- build.gradle
Recommended upgrades in Android Studio 4.1.3 (released)
> Updated kotlin and gradle plugins

- README.md
Apparently installation instructions and permissions were not visible enough for newcomers.
Closes #753
> Promote Getting Started in Readme

- rxandroidble/src/main/java/com/polidea/rxandroidble2/exceptions/BleGattException.java
Suggested change for issue #778
> PR for bleeding-edge GattStatus codes

- README.md
I should have used `tools:node="replace"` for these modifications
> Fix instructions to modify permissions

- sample-kotlin/src/main/kotlin/com/polidea/rxandroidble2/samplekotlin/example1_scanning/ScanActivity.kt
- sample-kotlin/src/main/kotlin/com/polidea/rxandroidble2/samplekotlin/example1a_background_scanning/BackgroundScanActivity.kt
- sample-kotlin/src/main/kotlin/com/polidea/rxandroidble2/samplekotlin/util/ScanPermission.kt
- sample/src/main/java/com/polidea/rxandroidble2/sample/example1_scanning/ScanActivity.java
- sample/src/main/java/com/polidea/rxandroidble2/sample/example1a_background_scanning/BackgroundScanActivity.java
- sample/src/main/java/com/polidea/rxandroidble2/sample/util/ScanPermission.java
> Sample apps fixes

- mockrxandroidble/src/main/java/com/polidea/rxandroidble2/mockrxandroidble/RxBleClientMock.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/ClientComponent.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/RxBleClient.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/RxBleClientImpl.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/util/CheckerConnectPermission.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/util/CheckerPermission.java
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/RxBleClientTest.groovy
- rxandroidble/src/test/groovy/com/polidea/rxandroidble2/internal/util/LocationServicesStatusApi23Test.groovy
- sample-kotlin/src/main/kotlin/com/polidea/rxandroidble2/samplekotlin/example2_connection/ConnectionExampleActivity.kt
- sample-kotlin/src/main/kotlin/com/polidea/rxandroidble2/samplekotlin/util/ConnectPermission.kt
- sample/src/main/java/com/polidea/rxandroidble2/sample/example2_connection/ConnectionExampleActivity.java
- sample/src/main/java/com/polidea/rxandroidble2/sample/util/ConnectPermission.java
> Added Android 12 connect permission helper functions

- dagger-library-shadow/build.gradle
- gradle.properties
- rxandroidble/build.gradle
- rxandroidble3/build.gradle
> Fixed build for apps using Dagger (regression)

- sample-kotlin/src/main/kotlin/com/polidea/rxandroidble2/samplekotlin/example2_connection/ConnectionExampleActivity.kt
Wrong permission is checked in the sample-kotlin app
Fixes #824
> Fix connection permission check in sample-kotlin app

- .github/workflows/gradle-actions.yml
Bumped actions/checkout@v2 => @v3 and actions/setup-java@2.2.0 => @3.11.0
> Bumped actions/checkout and actions/setup-java

- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/connection/RxBleGattCallback.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/logger/LoggerUtil.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/operations/CharacteristicLongWriteOperation.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/operations/CharacteristicReadOperation.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/operations/CharacteristicWriteOperation.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/operations/DescriptorReadOperation.java
- rxandroidble/src/main/java/com/polidea/rxandroidble2/internal/operations/DescriptorWriteOperation.java
These methods pass characteristic and descriptor values explicitly.
> Prepare LoggerUtil for new BluetoothGattCallback methods
